import { StyleSheet } from "react-native";
import { appTheme, colors, fontSize } from "../../constants";

export const styles = StyleSheet.create({
  container: {
    backgroundColor: "#fff",
    flex: 1,
    justifyContent: "space-between",
  },
  typeVehicle: {
    marginTop: -35,
    flexDirection: "row",
    marginHorizontal: 15,
    justifyContent: "flex-end",
    zIndex: -1,
    marginBottom: 10,
  },
  imgVehicle: { width: 25, height: 25, marginRight: 10 },
  textVehicle: {
    fontSize: fontSize.large,
    fontFamily: "Roboto_500",
    color: colors.text,
  },
  // box, 75 header, 62 button bottom, 44 safeview top, 20 safeview bottom, 20 margin bottom
  scrollView: {
    height: appTheme.HEIGHT - 75 - 62 - 84,
    marginBottom: 20,
  },
  bottomControl: { marginHorizontal: 15, marginBottom: 20 },
  boxClose: {
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: "#FBFCFE",
    paddingVertical: 13,
    paddingHorizontal: 20,
    borderColor: colors.red,
  },
  boxStart: {
    marginLeft: 10,
    borderRadius: 8,
    backgroundColor: colors.primary,
    paddingVertical: 13,
    paddingHorizontal: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    width: appTheme.WIDTH - 30 - 74 - 10,
  },
  textStart: {
    color: colors.white,
    fontFamily: "Roboto_500",
    fontSize: fontSize.h4,
  },
  boxModal: {
    margin: 0,
    position: "absolute",
    width: "100%",
    top: appTheme.HEIGHT - 250,
  },
  boxRadio: {
    backgroundColor: colors.white,
    height: 250,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.3,
    justifyContent: "space-between",
    paddingBottom: 40,
  },
  boxConfirm: {
    marginLeft: 10,
    borderRadius: 8,
    backgroundColor: colors.primary,
    paddingVertical: 13,
    paddingHorizontal: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    width: appTheme.WIDTH - 60,
  },
  textConfirm: {
    color: colors.white,
    fontFamily: "Roboto_500",
    fontSize: fontSize.h4,
  },
  buttonClose: {
    width: 50,
    height: 50,
    backgroundColor: colors.white,
    borderRadius: 100,
    position: "absolute",
    top: -60,
    left: 20,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.3,
    shadowRadius: 15,
    elevation: 0,
    borderRadius: 100,
    borderWidth: 0.5,
    borderColor: colors.gray,
  },
});
